services:
  web:
    build:
      context: ..
      dockerfile: infra/Dockerfile.web
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - api

  api:
    build:
      context: ..
      dockerfile: infra/Dockerfile.api
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - PORT=4000