services:
  web:
    build:
      context: ..
      dockerfile: infra/Dockerfile.web
    ports:
      - "8080:80"
    environment:
      - NODE_ENV=production
    depends_on:
      - api
    networks:
      - munfish-network

  api:
    build:
      context: ..
      dockerfile: infra/Dockerfile.api
    environment:
      - NODE_ENV=production
      - PORT=4000
    networks:
      - munfish-network

networks:
  munfish-network:
    driver: bridge